# Generated by Django 4.1.6 on 2023-07-25 00:34

from django.db import migrations
from gene.models import CarrierType, GeneCategory


def build_defaults(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    XenoType = apps.get_model("gene", "XenoType")
    Gene = apps.get_model("gene", "Gene")
    db_alias = schema_editor.connection.alias
    ENDO = CarrierType.ENDO
    XENO = CarrierType.XENO

    XenoType.objects.using(db_alias).bulk_create([
        XenoType(label=label, carrier_type=carrier_type, vanilla=True) for label, carrier_type in [
            ('Dirtmole', ENDO),
            ('Genie', XENO),
            ('Highmate', XENO),
            ('Hussar', XENO),
            ('Impid', ENDO),
            ('Neanderthal', ENDO),
            ('Pigskin', ENDO),
            ('Sanguophage', XENO),
            ('Waster', ENDO),
            ('Yttakin', ENDO),
        ]
    ])

    # create non-dynamic genes
    Gene.objects.using(db_alias).bulk_create([
        Gene(label=label, def_name=def_name, category=category, vanilla=True) for def_name, label, category in [
            # GeneDefs_Abilities.xml
            ('FireSpew', 'fire spew', GeneCategory.SPECIAL_ABILITIES),
            ('FoamSpray', 'foam spray', GeneCategory.SPECIAL_ABILITIES),
            ('LongjumpLegs', 'longjump legs', GeneCategory.SPECIAL_ABILITIES),
            ('AnimalWarcall', 'animal warcall', GeneCategory.SPECIAL_ABILITIES),
            ('Bloodfeeder', 'bloodfeeder', GeneCategory.SPECIAL_ABILITIES),
            ('Coagulate', 'coagulate', GeneCategory.SPECIAL_ABILITIES),
            ('XenogermReimplanter', 'gene implanter', GeneCategory.SPECIAL_ABILITIES),
            ('PiercingSpine', 'piercing spine', GeneCategory.SPECIAL_ABILITIES),
            ('AcidSpray', 'acid spray', GeneCategory.SPECIAL_ABILITIES),
            # GeneDefs_Cosmetic.xml
            ('Hair_BaldOnly', 'no hair', GeneCategory.COSMETIC),
            ('Hair_ShortOnly', 'short-haired', GeneCategory.COSMETIC),
            ('Hair_LongOnly', 'long-haired', GeneCategory.COSMETIC),
            ('Hair_Grayless', 'grayless hair', GeneCategory.COSMETIC),
            ('Beard_BushyOnly', 'only bushy beards', GeneCategory.COSMETIC),
            ('Beard_NoBeardOnly', 'beardless', GeneCategory.COSMETIC),
            ('Beard_Always', 'unisex beards', GeneCategory.COSMETIC),
            ('Hair_SnowWhite', 'snow-white hair', GeneCategory.COSMETIC),
            ('Hair_InkBlack', 'ink-black hair', GeneCategory.COSMETIC),
            ('Hair_Gray', 'gray hair', GeneCategory.COSMETIC),
            ('Hair_DarkBlack', 'dark-black hair', GeneCategory.COSMETIC),
            ('Hair_MidBlack', 'mid-black hair', GeneCategory.COSMETIC),
            ('Hair_DarkReddish', 'dark-reddish hair', GeneCategory.COSMETIC),
            ('Hair_DarkSaturatedReddish', 'dark-brown hair', GeneCategory.COSMETIC),
            ('Hair_DarkBrown', 'brown hair', GeneCategory.COSMETIC),
            ('Hair_ReddishBrown', 'reddish-brown hair', GeneCategory.COSMETIC),
            ('Hair_SandyBlonde', 'sandy-blonde hair', GeneCategory.COSMETIC),
            ('Hair_Blonde', 'blonde hair', GeneCategory.COSMETIC),
            ('Hair_Pink', 'pink hair', GeneCategory.COSMETIC),
            ('Hair_LightPurple', 'purple hair', GeneCategory.COSMETIC),
            ('Hair_LightBlue', 'blue hair', GeneCategory.COSMETIC),
            ('Hair_LightTeal', 'teal hair', GeneCategory.COSMETIC),
            ('Hair_LightGreen', 'green hair', GeneCategory.COSMETIC),
            ('Hair_LightOrange', 'orange hair', GeneCategory.COSMETIC),
            ('Hair_BrightRed', 'red hair', GeneCategory.COSMETIC),
            ('Skin_InkBlack', 'ink black skin', GeneCategory.COSMETIC),
            ('Skin_SlateGray', 'slate gray skin', GeneCategory.COSMETIC),
            ('Skin_LightGray', 'light gray skin', GeneCategory.COSMETIC),
            ('Skin_SheerWhite', 'sheer white skin', GeneCategory.COSMETIC),
            ('Skin_Blue', 'blue skin', GeneCategory.COSMETIC),
            ('Skin_Purple', 'purple skin', GeneCategory.COSMETIC),
            ('Skin_PaleRed', 'pale red skin', GeneCategory.COSMETIC),
            ('Skin_DeepRed', 'deep red skin', GeneCategory.COSMETIC),
            ('Skin_PaleYellow', 'pale yellow skin', GeneCategory.COSMETIC),
            ('Skin_DeepYellow', 'deep yellow skin', GeneCategory.COSMETIC),
            ('Skin_Orange', 'orange skin', GeneCategory.COSMETIC),
            ('Skin_Green', 'green skin', GeneCategory.COSMETIC),
            ('Furskin', 'furskin', GeneCategory.COSMETIC),
            ('Eyes_Red', 'red eyes', GeneCategory.COSMETIC),
            ('Eyes_Gray', 'gray eyes', GeneCategory.COSMETIC),
            ('Brow_Heavy', 'heavy brow', GeneCategory.COSMETIC),
            ('Tail_Furry', 'furry tail', GeneCategory.COSMETIC),
            ('Tail_Smooth', 'smooth tail', GeneCategory.COSMETIC),
            ('FacialRidges', 'facial ridges', GeneCategory.COSMETIC),
            # GeneDefs_Endogenes.xml
            ('Body_Fat', 'fat body', GeneCategory.COSMETIC),
            ('Body_Thin', 'thin body', GeneCategory.COSMETIC),
            ('Body_Hulk', 'hulk body', GeneCategory.COSMETIC),
            ('Body_Standard', 'standard body', GeneCategory.COSMETIC),
            ('Ears_Human', 'human ears', GeneCategory.COSMETIC),
            ('Ears_Pig', 'pig ears', GeneCategory.COSMETIC),
            ('Ears_Floppy', 'floppy ears', GeneCategory.COSMETIC),
            ('Ears_Cat', 'cat ears', GeneCategory.COSMETIC),
            ('Ears_Pointed', 'pointed ears', GeneCategory.COSMETIC),
            ('Nose_Human', 'human nose', GeneCategory.COSMETIC),
            ('Nose_Pig', 'pig nose', GeneCategory.COSMETIC),
            ('Jaw_Baseline', 'human jaw', GeneCategory.COSMETIC),
            ('Jaw_Heavy', 'heavy jaw', GeneCategory.COSMETIC),
            ('Head_Gaunt', 'gaunt head', GeneCategory.COSMETIC),
            ('Hands_Human', 'human hands', GeneCategory.MISCELLANEOUS),
            ('Hands_Pig', 'trotter hands', GeneCategory.MISCELLANEOUS),
            ('ElongatedFingers', 'elongated fingers', GeneCategory.MISCELLANEOUS),
            ('Headbone_Human', 'human headbone', GeneCategory.COSMETIC),
            ('Headbone_MiniHorns', 'mini-horns', GeneCategory.COSMETIC),
            ('Headbone_CenterHorn', 'center-horn', GeneCategory.COSMETIC),
            ('Voice_Human', 'human voice', GeneCategory.COSMETIC),
            ('VoicePig', 'pig voice', GeneCategory.COSMETIC),
            ('VoiceRoar', 'roar voice', GeneCategory.COSMETIC),
            # GeneDefs_Health.xml
            ('WoundHealing_Slow', 'slow wound healing', GeneCategory.HEALTH),
            ('WoundHealing_Fast', 'fast wound healing', GeneCategory.HEALTH),
            ('WoundHealing_SuperFast', 'superfast wound healing', GeneCategory.HEALTH),
            ('Immunity_Weak', 'weak immunity', GeneCategory.HEALTH),
            ('Immunity_Strong', 'strong immunity', GeneCategory.HEALTH),
            ('Immunity_SuperStrong', 'super immunity', GeneCategory.HEALTH),
            ('ToxicEnvironmentResistance_Partial', 'partial antitoxic lungs', GeneCategory.RESISTANCE_AND_SENSITIVITY),
            ('ToxicEnvironmentResistance_Total', 'total antitoxic lungs', GeneCategory.RESISTANCE_AND_SENSITIVITY),
            ('Sterile', 'sterile', GeneCategory.REPRODUCTION),
            ('Fertile', 'fertile', GeneCategory.REPRODUCTION),
            ('Superclotting', 'superclotting', GeneCategory.HEALTH),
            # GeneDefs_Misc.xml
            ('KindInstinct', 'kind instinct', GeneCategory.VIOLENCE),
            ('ViolenceDisabled', 'violence disabled', GeneCategory.VIOLENCE),
            ('Nearsighted', 'nearsighted', GeneCategory.MISCELLANEOUS),
            ('StrongStomach', 'strong stomach', GeneCategory.MISCELLANEOUS),
            ('DarkVision', 'dark vision', GeneCategory.MISCELLANEOUS),
            ('KillThirst', 'kill thirst', GeneCategory.VIOLENCE),
            ('FireResistant', 'fire resistant', GeneCategory.RESISTANCE_AND_SENSITIVITY,),
            ('Inbred', 'inbred', GeneCategory.MISCELLANEOUS),
            ('RobustDigestion', 'robust digestion', GeneCategory.MISCELLANEOUS),
            ('Instability_Mild', 'mild cell instability', GeneCategory.MISCELLANEOUS),
            ('Instability_Major', 'major cell instability', GeneCategory.MISCELLANEOUS),
            ('PsychicBonding', 'psychic bonding', GeneCategory.PSYCHIC),
            ('PollutionRush', 'pollution stimulus', GeneCategory.MISCELLANEOUS),
            ('Unstoppable', 'unstoppable', GeneCategory.MISCELLANEOUS),
            ('NakedSpeed', 'naked speed', GeneCategory.MOVEMENT),
            # GeneDefs_Sanguophage.xml
            ('Hemogenic', 'hemogenic', GeneCategory.HEMOGEN),
            ('HemogenDrain', 'hemogen drain', GeneCategory.HEMOGEN),
            ('FireWeakness', 'tinderskin', GeneCategory.RESISTANCE_AND_SENSITIVITY),
            ('FireTerror', 'pyrophobia', GeneCategory.RESISTANCE_AND_SENSITIVITY),
            ('PerfectImmunity', 'perfect immunity', GeneCategory.ARCHITE),
            ('DiseaseFree', 'non-senescent', GeneCategory.ARCHITE),
            ('TotalHealing', 'scarless', GeneCategory.ARCHITE),
            ('Deathrest', 'deathrest', GeneCategory.HEMOGEN),
            ('Ageless', 'ageless', GeneCategory.ARCHITE),
            ('Deathless', 'deathless', GeneCategory.ARCHITE),
            ('ArchiteMetabolism', 'archite metabolism', GeneCategory.ARCHITE),
            # GeneDefs_Spectrum.xml
            ('MinTemp_SmallIncrease', 'cold weakness', GeneCategory.TEMPERATURE),
            ('MinTemp_SmallDecrease', 'cold tolerant', GeneCategory.TEMPERATURE),
            ('MinTemp_LargeDecrease', 'cold super-tolerant', GeneCategory.TEMPERATURE),
            ('MaxTemp_LargeIncrease', 'heat super-tolerant', GeneCategory.TEMPERATURE),
            ('MaxTemp_SmallIncrease', 'heat tolerant', GeneCategory.TEMPERATURE),
            ('MaxTemp_SmallDecrease', 'heat weakness', GeneCategory.TEMPERATURE),
            ('PsychicAbility_Deaf', 'psychically deaf', GeneCategory.PSYCHIC),
            ('PsychicAbility_Dull', 'psychically dull', GeneCategory.PSYCHIC),
            ('PsychicAbility_Enhanced', 'psy-sensitive', GeneCategory.PSYCHIC),
            ('PsychicAbility_Extreme', 'super psy-sensitive', GeneCategory.PSYCHIC),
            ('MoveSpeed_Slow', 'slow runner', GeneCategory.MOVEMENT),
            ('MoveSpeed_Quick', 'fast runner', GeneCategory.MOVEMENT),
            ('MoveSpeed_VeryQuick', 'very fast runner', GeneCategory.MOVEMENT),
            ('Beauty_VeryUgly', 'very unattractive', GeneCategory.BEAUTY),
            ('Beauty_Ugly', 'unattractive', GeneCategory.BEAUTY),
            ('Beauty_Pretty', 'attractive', GeneCategory.BEAUTY),
            ('Beauty_Beautiful', 'very attractive', GeneCategory.BEAUTY),
            ('Learning_Slow', 'slow study', GeneCategory.MISCELLANEOUS),
            ('Learning_Fast', 'quick study', GeneCategory.MISCELLANEOUS),
            ('Mood_Depressive', 'very unhappy', GeneCategory.MOOD),
            ('Mood_Pessimist', 'unhappy', GeneCategory.MOOD),
            ('Mood_Optimist', 'happy', GeneCategory.MOOD),
            ('Mood_Sanguine', 'very happy', GeneCategory.MOOD),
            ('ToxResist_Partial', 'tox resistance', GeneCategory.RESISTANCE_AND_SENSITIVITY),
            ('ToxResist_Total', 'tox immunity', GeneCategory.RESISTANCE_AND_SENSITIVITY),
            ('Delicate', 'delicate', GeneCategory.PAIN),
            ('Robust', 'robust', GeneCategory.PAIN),
            ('Pain_Reduced', 'reduced pain', GeneCategory.PAIN),
            ('Pain_Extra', 'extra pain', GeneCategory.PAIN),
            ('Aggression_DeadCalm', 'dead calm', GeneCategory.VIOLENCE),
            ('Aggression_Aggressive', 'aggressive', GeneCategory.VIOLENCE),
            ('Aggression_HyperAggressive', 'hyper-aggressive', GeneCategory.VIOLENCE),
            ('VerySleepy', 'very sleepy', GeneCategory.SLEEP),
            ('Sleepy', 'sleepy', GeneCategory.SLEEP),
            ('LowSleep', 'low sleep', GeneCategory.SLEEP),
            ('Neversleep', 'never sleep', GeneCategory.SLEEP),
            ('MeleeDamage_Weak', 'weak melee damage', GeneCategory.VIOLENCE),
            ('MeleeDamage_Strong', 'strong melee damage', GeneCategory.VIOLENCE),
            ('UVSensitivity_Mild', 'mild UV sensitivity', GeneCategory.RESISTANCE_AND_SENSITIVITY),
            ('UVSensitivity_Intense', 'intense UV sensitivity', GeneCategory.RESISTANCE_AND_SENSITIVITY),
            ('Libido_Low', 'low libido', GeneCategory.REPRODUCTION),
            ('Libido_High', 'high libido', GeneCategory.REPRODUCTION),
        ]
    ])

    # create the dynamic genes from XenotypeDefs.xml
    skills = (
        ('Shooting', 'shooting'),
        ('Melee', 'melee'),
        ('Construction', 'construction'),
        ('Mining', 'mining'),
        ('Cooking', 'cooking'),
        ('Plants', 'plants'),
        ('Animals', 'animals'),
        ('Crafting', 'crafting'),
        ('Artistic', 'artistic'),
        ('Medicine', 'medical'),
        ('Social', 'social'),
        ('Intellectual', 'intellectual'),
    )
    aptitude_genes = []
    for skill_def_name, skill_label in skills:
        aptitude_genes.extend([
            ('AptitudeTerrible_%s' % skill_def_name, 'Awful %s' % skill_label.title()),
            ('AptitudePoor_%s' % skill_def_name, 'Poor %s' % skill_label.title()),
            ('AptitudeStrong_%s' % skill_def_name, 'Strong %s' % skill_label.title()),
            ('AptitudeRemarkable_%s' % skill_def_name, 'Great %s' % skill_label.title()),
        ])

    Gene.objects.using(db_alias).bulk_create([
        Gene(
            label=label, def_name=def_name, category=GeneCategory.APTITUDES, vanilla=True
        ) for def_name, label in aptitude_genes
    ])

    drugs = (
        ('Alcohol', 'alcohol'),
        ('GoJuice', 'go-juice'),
        ('Smokeleaf', 'Smokeleaf'),
        ('WakeUp', 'wake-up'),
        ('Psychite', 'psychite'),
    )
    drug_genes = []
    for drug_def_name, drug_label in drugs:
        drug_genes.extend([
            ('ChemicalDependency_%s' % drug_def_name, '%s dependency' % drug_label.title()),
            ('AddictionResistant_%s' % drug_def_name, '%s resistant' % drug_label.title()),
            ('AddictionImmune_%s' % drug_def_name, '%s impervious' % drug_label.title()),
        ])

    Gene.objects.using(db_alias).bulk_create([
        Gene(
            label=label, def_name=def_name, category=GeneCategory.DRUGS, vanilla=True
        ) for def_name, label in drug_genes
    ])


def unbuild_defaults(apps, schema_editor):
    XenoType = apps.get_model("gene", "XenoType")
    Gene = apps.get_model("gene", "Gene")
    db_alias = schema_editor.connection.alias
    XenoType.objects.using(db_alias).filter(vanilla=True).delete()
    Gene.objects.using(db_alias).filter(vanilla=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('gene', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(build_defaults, unbuild_defaults),
    ]
