# Generated by Django 4.2.3 on 2023-07-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0004_xeno_gene_pairings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='icon',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
