# Generated by Django 4.2.3 on 2023-07-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0006_populate_gene_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='color',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
