# Generated by Django 4.2.3 on 2023-07-26 02:13

from django.db import migrations
from gene.utils import generate_color

def set_color(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Gene = apps.get_model("gene", "Gene")
    db_alias = schema_editor.connection.alias
    object_list = []
    for gene in Gene.objects.using(db_alias).all():
        gene.color = generate_color(gene)
        object_list.append(gene)
    Gene.objects.using(db_alias).bulk_update(object_list, ['color'])

def unset_color(apps, schema_editor):
    pass  # no need


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0007_gene_color'),
    ]

    operations = [
        migrations.RunPython(set_color, unset_color),
    ]
